version: '2'
services:
  auto-sklearn:
    build: ./docker/auto-sklearn
    image: auto-sklearn:latest
    volumes:
      - ./:/home/jovyan/work
    working_dir: /home/jovyan/work
    ports:
      - 8888:8888
    environment: 
      - JUPYTER_ENABLE_LAB=yes
  
  scikit-multiflow:
    build: ./docker/scikit-multiflow
    image: scikit-multiflow:latest
    volumes:
      - ./:/home/jovyan/work
    working_dir: /home/jovyan/work
    ports:
      - 8889:8888
    environment: 
      - JUPYTER_ENABLE_LAB=yes

  h2o:
    build: ./docker/h2o
    image: h2o:latest
    volumes:
      - ./:/home/jovyan/work
    working_dir: /home/jovyan/work
    ports:
      - 8890:8888
    environment: 
      - JUPYTER_ENABLE_LAB=yes
  
  spark:
    build: ./docker/spark
    image: spark:latest
    volumes:
      - ./:/home/jovyan/work
    working_dir: /home/jovyan/work
    ports:
      - 8891:8888
    environment: 
      - JUPYTER_ENABLE_LAB=yes

  # Kafka Cluster
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,HOST://localhost:9092